# Generated by Django 6.0.4 on 2026-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedfile',
            name='session',
        ),
        migrations.RemoveField(
            model_name='selectedcolumn',
            name='session',
        ),
        migrations.AddField(
            model_name='mergesession',
            name='all_files',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mergesession',
            name='selected_columns',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ColumnMapping',
        ),
        migrations.DeleteModel(
            name='MergedFile',
        ),
        migrations.DeleteModel(
            name='SelectedColumn',
        ),
    ]
